CREATE TABLE IF NOT EXISTS endpoint_hits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app varchar(100) NOT NULL,
    uri varchar(150) NOT NULL,
    ip  varchar(16) NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL,

    CONSTRAINT pk_endpoint_hits PRIMARY KEY (id)
);